 SELECT
    A1.SYSCODE,
    A1.SYSVALUE AS TRD_ORGID,
    A2.ORGCODE AS ORGID,
    A2.ORGNAME,
    A2.ORGFULLNAME,
    A3.ORGCODE AS PARENTORGID,
    SPLIT_PART((A2.ORGFULLNAME)::TEXT, '/'::TEXT, (TEMP.GETARRAYLENGTH1(A2.ORGFULLNAME) - 1)) AS PARENTORGNAME
   FROM ((DWODATA.COS_COS_MAIN_DATA_ORGCODEMAPPING A1
      LEFT JOIN DWODATA.COS_COS_MAIN_DATA_ORGANIZATION A2 ON ((((((A1.ORGID)::TEXT = (A2.ORGID)::TEXT) AND ((A2.ORGSTATUS)::TEXT = '1'::TEXT)) AND (A2.END_DT = '2999-12-31'::DATE)) AND (A2.DEL_IND <> 'D'::BPCHAR))))
      LEFT JOIN DWODATA.COS_COS_MAIN_DATA_ORGANIZATION A3 ON (((((A2.PARENTORGID)::TEXT = (A3.ORGID)::TEXT) AND (A3.END_DT = '2999-12-31'::DATE)) AND (A3.DEL_IND <> 'D'::BPCHAR))))
  WHERE -- ((((A1.END_DT = '2999-12-31'::DATE) AND (A1.DEL_IND <> 'D'::BPCHAR)) AND ((A1.MAPPINGSTATUS)::TEXT = '1'
